// use log::error;

// pub fn test_log_error_inside_module() {
//     error!("This is a test error message from my_secret_module issued by log.");
// }
